name: Testing
on: [push, pull_request]
jobs:
  Run-server-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: echo "Server tests"
      - run: npm install
      - run: npm run test
