name: Run server lint & test
on: 
  pull_request:
    paths:
      - 'server/**'
jobs:
  Run-server-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: npm install
        working-directory: ./server
        run: npm install
      - name: npm lint
        working-directory: ./server
        run: npm run lint -- --fix
      - name: npm test
        working-directory: ./server
        env: 
          MONGO_TEST_URI : ${{ secrets.MONGO_MESSAGES_TEST_URI }}
          PROJECT_ID : ${{ secrets.SERVER_FIREBASE_PROJECT_ID }}
          PRIVATE_KEY : ${{ secrets.SERVER_FIREBASE_PRIVATE_KEY }}
          CLIENT_EMAIL : ${{ secrets.SERVER_FIREBASE_CLIENT_EMAIL }}
          FIREBASE_APP_API_KEY : ${{ secrets.SERVER_FIREBASE_APP_API_KEY }}
          TEST_USERNAME : ${{ secrets.SERVER_TEST_USERNAME }}
          TEST_PASSWORD : ${{ secrets.SERVER_TEST_PASSWORD }}
        run: npm run test