name: Build image and push heroku
on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_TEST_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: ./server
          healthcheck: https://kalle-studio-test.herokuapp.com/api/v1/health
          checkstring: ok
          delay: 3
          rollbackonhealthcheckfailed: true
  update-server-tag:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
