name: Run server lint & test
on: 
  pull_request:
    paths:
      - 'server/**'
  push:
    paths:
      - 'server/**'
jobs:
  Run-server-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: npm install
        working-directory: ./server
        run: npm install --production
      - name: npm lint
        working-directory: ./server
        run: npm run lint -- --fix
      - name: npm test
        working-directory: ./server
        run: npm run test
