name: Test version tag
on:
  push:
  workflow_dispatch:
jobs:
  poop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello tags"
  update-server-tag:
    runs-on: ubuntu-latest
    env:
      isMajor: contains(join(github.event.commits.*.message, ' '), '#major')
      isMinor: contains(join(github.event.commits.*.message, ' '), '#minor')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "1"
      - name: major
        uses: anothrNick/github-tag-action@1.34.0
        if: ${{isMajor && !isminor}}
        run: echo "major"
      - name: minor
        uses: anothrNick/github-tag-action@1.34.0
        if: ${{!isMajor && isminor}}
        run: echo "minor"
      - name: patch
        uses: anothrNick/github-tag-action@1.34.0
        if: ${{!isMajor && !isminor}}
        run: echo "patch"
