name: Testing
on: [push, pull_request]
jobs:
  Run-server-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install and test
        working-directory: ./server
        run: |
          npm install
          npm run lint -- --fix
          npm run test
