name: Test version tag
on:
  push:
  workflow_dispatch:
jobs:
  update-server-tag:
    runs-on: ubuntu-latest
    env:
      isMajor: ${{contains(join(github.event.commits.*.message, ' '), '#major')}}
      isMinor: ${{contains(join(github.event.commits.*.message, ' '), '#minor')}}
    steps:
      - name: test
        if: ${{env.isMajor}}
        run: echo "ma $isMajor mi $isMinor"
