name: Test version tag
on:
  push:
  workflow_dispatch:
jobs:
  poop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello tags"
  update-server-tag:
    runs-on: ubuntu-latest
    needs: poop
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        TAG_CONTEXT: branch
        DRY_RUN: true
        
