name: Test version tag
on:
  push:
  workflow_dispatch:
jobs:
  update-server-tag:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: ${{contains(join(github.event.commits.*.message, ' '), '#major')}}
        run: echo "ma $isMajor mi $isMinor"
        env:
          isMajor: ${{contains(join(github.event.commits.*.message, ' '), '#major')}}
          isMinor: contains(join(github.event.commits.*.message, ' '), '#minor')

